### PR TITLE
replace the current awaeful site with something nicer?

### PR DESCRIPTION
**Pull request by azyth**
obviously still has to have a bunch of stuff done to it, but what you think?

### CODE REVIEW

**Comment by azyth** [comment]
@kyleoliveira take a look

**Comment by kyleoliveira** [comment]
Sure.

**Comment by azyth** [comment]
it is ready to post, need to get the links working for all the contacts and stuff, but basic info is all there, and video seem to work locally for me, wont know for sure how well it is till we merge .... but i say we post it asap, the other one is soo bad.

**Comment by kyleoliveira** [comment]
Looks like it's go for merge to master whenever you're ready.

**Pull request merged**
